apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod
 labels: 
  app: nginx
  demo: service
spec:
  containers:
  - name: nginx-pod
    image: nginx # nginx is the default image, hence will pick/pull from dockerhub
    ports:
    - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
 name: nginx-service
spec:
 selector: #selcetor is the key word to recall the labels
  app: nginx
  demo: service
 ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 #container port
    #nodePort: 34000 we can open the required port
    
