apiVersion: apps/v1  # Deployement definition start
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    demo: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      demo: deployment # Deployment definition end
  template: #pod definition starts
    metadata:
      labels:
        app: nginx
        demo: deployment
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80 # pod definition end
---
apiVersion: v1
kind: Service
metadata:
 name: nginx-service
spec:
 selector: #selcetor is the key word to recall the labels
  app: nginx
  demo: deployment
 ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 #container port
    #nodePort: 34000 we can open the required port