apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  namespace: roboshop # if we dont mention the specfied namespace then it will create in default namespace
spec:
  containers:
  - name: hello-pod
    image: nginx # nginx is the default image, hence will pick/pull from dockerhub
    ports:
    - containerPort: 80