apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  namespace: roboshop # if we dont mention the specfied namespace then it will create in default namespace
spec:
  containers:
  - name: hello-pod
    image: nginx # nginx is the default image, hence will pick/pull from dockerhub
    ports:
    - containerPort: 80
    resources:   #we can restrict the resources consumed by containers...  This is the advantage in kubernetes 
      requests:
        cpu: "100m"
        memory: "68Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"

      